
language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      arch: amd64
      cache: apt
      addons:
        apt:
          update: true
    - os: linux
      dist: focal
      arch: arm64
      cache: apt
      addons:
        apt:
          update: true
    - os: windows
    - os: osx
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
          - python3
          - cmake
          - pkg-config
          - gtksourceviewmm3
          - gnome-icon-theme
          - gspell
          - libxml++
          - cpputest
          - curl
          - uchardet

compiler:
  - gcc

before_install:
- |-
    case $TRAVIS_OS_NAME in
      linux)
        sudo apt install build-essential cmake libgtkmm-3.0-dev xvfb
        sudo apt install libgtksourceviewmm-3.0-dev libxml++2.6-dev libsqlite3-dev
        sudo apt install libcpputest-dev gettext libgspell-1-dev libcurl4-openssl-dev libuchardet-dev
        ;;
      windows)
        [[ ! -f C:/tools/msys64/msys2_shell.cmd ]] && rm -rf C:/tools/msys64
        choco uninstall -y mingw
        choco upgrade --no-progress -y msys2
        export msys2='cmd //C RefreshEnv.cmd '
        export msys2+='& set MSYS=winsymlinks:nativestrict '
        export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
        export mingw64="$msys2 -mingw64 -full-path -here -c "\"\$@"\" --"
        export msys2+=" -msys2 -c "\"\$@"\" --"
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-toolchain
        ## Install more MSYS2 packages from https://packages.msys2.org/base here
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-cmake
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gtkmm3
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gtksourceviewmm3
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-libxml++2.6
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-sqlite3
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-gspell
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-curl
        $msys2 pacman --sync --noconfirm --needed mingw-w64-x86_64-uchardet
        taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
        export PATH=/C/tools/msys64/mingw64/bin:$PATH
        export MAKE=mingw32-make  # so that Autotools can find it
        ;;
    esac
install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        $mingw64 wget https://github.com/cpputest/cpputest/releases/download/v3.8/cpputest-3.8.tar.gz
        $mingw64 tar xf cpputest-3.8.tar.gz
        cd cpputest-3.8
        $mingw64 ./autogen.sh
        $mingw64 ./configure --disable-memory-leak-detection
        $mingw64 mingw32-make
        $mingw64 mingw32-make install
        ;;
    esac
script:
- |-
    case $TRAVIS_OS_NAME in
      linux)
        cd ${TRAVIS_BUILD_DIR}
        xvfb-run ./build.sh Release
        ;;
      windows)
        cd ${TRAVIS_BUILD_DIR}
        $mingw64 ./build.sh Release
        ;;
      osx)
        cd ${TRAVIS_BUILD_DIR}
        mkdir build && cd build
        cmake ../
        make -j$(sysctl -n hw.ncpu)
        ./tests/run_tests
        ;;
    esac
